services:

  postgres:
    image: postgres:15
    platform: linux/amd64
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      AUDIT_DB_HOST: airflow_postgres
      AUDIT_DB_PORT: 5432
      AUDIT_DB_NAME: airflow
      AUDIT_DB_USER: airflow
      AUDIT_DB_PASSWORD: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-init:
    image: apache/airflow:2.8.0
    container_name: airflow_init
    depends_on:
      - postgres
    restart: "no"
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      DATALAKE_PATH: /opt/airflow/datalake
      LOG_FOLDER: /opt/airflow/logs
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username airflow --password airflow --firstname Admin --lastname User --role Admin --email admin@example.com
      "

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      
      # Permite importar src
      PYTHONPATH: /opt/airflow
      DATALAKE_PATH: /opt/airflow/datalake
      LOG_FOLDER: /opt/airflow/logs

    # SMTP Configuration
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: "true"
      AIRFLOW__SMTP__SMTP_SSL: "false"
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${SENDER_EMAIL}
      
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./datalake:/opt/airflow/datalake
      - ./tests:/opt/airflow/tests

    ports:
      - "8080:8080"

    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

      # Permite importar src
      PYTHONPATH: /opt/airflow
      DATALAKE_PATH: /opt/airflow/datalake
      LOG_FOLDER: /opt/airflow/logs
      
    # SMTP Configuration
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_STARTTLS: "true"
      AIRFLOW__SMTP__SMTP_SSL: "false"
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${SENDER_EMAIL}
      
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./datalake:/opt/airflow/datalake
      - ./tests:/opt/airflow/tests

    command: scheduler

volumes:
  postgres-db-volume:
